### ISSUE TITLE
Zip file for bonnet compiler

### ISSUE THREAD

**Issue by minakhan01** [thunderblaster/aiy-vision-testing#1]
Hi, this link isn't working anymore: https://dl.google.com/dl/aiyprojects/vision/bonnet_model_compiler_2017_12_13.tgz. I was wondering if you had a copy of it and if you could send it to me. Need it urgently for a project.

Thanks!

**Comment by thunderblaster** [comment]
Sorry for the delay!  I don't have a copy of that laying around.  Unfortunately other things have taken my attention away from this project.  Good luck if you haven't already found a copy!
